version: '3'

services:

  api-users-app:
    container_name: api-users-app
    build: .docker/docker
    image: api-users-app
    depends_on:
      - api-users-mysql
      - api-users-redis
    volumes:
      - ./:/application:cached


  api-users-nginx:
    container_name: api-users-nginx
    image: nginx:alpine
    ports:
      - "8000:8000"
    volumes:
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
      - .docker/nginx/:/var/log/nginx/
    depends_on:
      - api-users-app
      - api-users-mysql
      - api-users-redis

  api-users-mysql:
    container_name: api-users-mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=users
    volumes:
      - api-users-mysql-data:/var/lib/mysql:cached

  api-users-redis:
    container_name: api-users-redis
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  api-users-mysql-data:
