version: '3'

services:

  api-users-app:
    container_name: api-users-app
    build: .docker/docker
    image: api-users-app
    depends_on:
      - api-users-mysql
      - api-users-redis
    volumes:
      - ./:/application:cached
    environment:
      - APP_ENV=local
      - APP_URL=http://dev.docker.com:8000
      - DB_HOST=api-users-mysql
      - DB_DATABASE=users
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - REDIS_HOST=api-users-redis
      - MAIL_HOST=smtp.mailtrap.io
      - MAIL_PORT=2525
      - MAIL_USERNAME=8c40019abeb8ba
      - MAIL_PASSWORD=0f1fa2683e9204
      - MAIL_ENCRYPTION=null
      - PAGINATE_PER_PAGE=15
      - AUTH_VERIFICATION_EXPIRE=60


  api-users-nginx:
    container_name: api-users-nginx
    image: nginx:alpine
    ports:
      - "8000:8000"
    volumes:
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
      - .docker/nginx/:/var/log/nginx/
    depends_on:
      - api-users-app
      - api-users-mysql
      - api-users-redis

  api-users-mysql:
    container_name: api-users-mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=users
    volumes:
      - api-users-mysql-data:/var/lib/mysql:cached

  api-users-redis:
    container_name: api-users-redis
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  api-users-mysql-data:
